# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hookdeck < Formula
  desc "Hookdeck CLI utility"
  homepage "https://hookdeck.com"
  version "1.0.0-beta.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.0.0-beta.1/hookdeck_1.0.0-beta.1_darwin_amd64.tar.gz"
    sha256 "9717b4e8129691cfcfac5b6ec75baa43359c2e2502388b33513bea3fd831f37f"

    def install
      bin.install "hookdeck"
      rm Dir["#{bin}/{hookdeck-completion.bash,hookdeck-completion.zsh}"]
      system bin/"hookdeck", "completion", "--shell", "bash"
      system bin/"hookdeck", "completion", "--shell", "zsh"
      bash_completion.install "hookdeck-completion.bash"
      zsh_completion.install "hookdeck-completion.zsh"
      (zsh_completion/"_hookdeck").write <<~EOS
        #compdef hookdeck
        _hookdeck () {
          local e
          e=$(dirname ${funcsourcetrace[1]%:*})/hookdeck-completion.zsh
          if [[ -f $e ]]; then source $e; fi
        }
      EOS
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.0.0-beta.1/hookdeck_1.0.0-beta.1_darwin_arm64.tar.gz"
    sha256 "b3595879f37799b4b66dde7ee499652b96e2e53b938afd2bb96b68eace30e09c"

    def install
      bin.install "hookdeck"
      rm Dir["#{bin}/{hookdeck-completion.bash,hookdeck-completion.zsh}"]
      system bin/"hookdeck", "completion", "--shell", "bash"
      system bin/"hookdeck", "completion", "--shell", "zsh"
      bash_completion.install "hookdeck-completion.bash"
      zsh_completion.install "hookdeck-completion.zsh"
      (zsh_completion/"_hookdeck").write <<~EOS
        #compdef hookdeck
        _hookdeck () {
          local e
          e=$(dirname ${funcsourcetrace[1]%:*})/hookdeck-completion.zsh
          if [[ -f $e ]]; then source $e; fi
        }
      EOS
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Hookdeck CLI! If this is your first time using the CLI, be sure to run `hookdeck login` first.
    EOS
  end
end
