# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hookdeck < Formula
  desc "Hookdeck CLI utility"
  homepage "https://hookdeck.com"
  version "0.6.4"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hookdeck/hookdeck-cli/releases/download/v0.6.4/hookdeck_0.6.4_darwin_arm64.tar.gz"
      sha256 "8a5f4a1d43d2bb6e20d545e56b91f346f70df7711197412724aa7876b1966ba0"

      def install
        bin.install "hookdeck"
        rm Dir["#{bin}/{hookdeck-completion.bash,hookdeck-completion.zsh}"]
        system bin/"hookdeck", "completion", "--shell", "bash"
        system bin/"hookdeck", "completion", "--shell", "zsh"
        bash_completion.install "hookdeck-completion.bash"
        zsh_completion.install "hookdeck-completion.zsh"
        (zsh_completion/"_hookdeck").write <<~EOS
          #compdef hookdeck
          _hookdeck () {
            local e
            e=$(dirname ${funcsourcetrace[1]%:*})/hookdeck-completion.zsh
            if [[ -f $e ]]; then source $e; fi
          }
        EOS
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hookdeck/hookdeck-cli/releases/download/v0.6.4/hookdeck_0.6.4_darwin_amd64.tar.gz"
      sha256 "b64a6784739ac660dc38abca34bc8ea18a56c04dc8ab72267edd98fc59353682"

      def install
        bin.install "hookdeck"
        rm Dir["#{bin}/{hookdeck-completion.bash,hookdeck-completion.zsh}"]
        system bin/"hookdeck", "completion", "--shell", "bash"
        system bin/"hookdeck", "completion", "--shell", "zsh"
        bash_completion.install "hookdeck-completion.bash"
        zsh_completion.install "hookdeck-completion.zsh"
        (zsh_completion/"_hookdeck").write <<~EOS
          #compdef hookdeck
          _hookdeck () {
            local e
            e=$(dirname ${funcsourcetrace[1]%:*})/hookdeck-completion.zsh
            if [[ -f $e ]]; then source $e; fi
          }
        EOS
      end
    end
  end

  def caveats; <<~EOS
    ❤ Thanks for installing the Hookdeck CLI! If this is your first time using the CLI, be sure to run `hookdeck login` first.
  EOS
  end
end
