# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hookdeck < Formula
  desc "Hookdeck CLI utility"
  homepage "https://hookdeck.com"
  version "0.6.2"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hookdeck/hookdeck-cli/releases/download/v0.6.2/hookdeck_0.6.2_mac-os_arm64.tar.gz"
      sha256 "8b65dc0e06dad4ffc2192673a563d9cae8fad4d887a8de2d3ba86b8bc21653fb"

      def install
        bin.install "hookdeck"
        rm Dir["#{bin}/{hookdeck-completion.bash,hookdeck-completion.zsh}"]
        system bin/"hookdeck", "completion", "--shell", "bash"
        system bin/"hookdeck", "completion", "--shell", "zsh"
        bash_completion.install "hookdeck-completion.bash"
        zsh_completion.install "hookdeck-completion.zsh"
        (zsh_completion/"_hookdeck").write <<~EOS
          #compdef hookdeck
          _hookdeck () {
            local e
            e=$(dirname ${funcsourcetrace[1]%:*})/hookdeck-completion.zsh
            if [[ -f $e ]]; then source $e; fi
          }
        EOS
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hookdeck/hookdeck-cli/releases/download/v0.6.2/hookdeck_0.6.2_mac-os_x86_64.tar.gz"
      sha256 "1ad63cf374a366ec12ae0fff691ca9670e6abd2b00ca3026e12bc702bbf26136"

      def install
        bin.install "hookdeck"
        rm Dir["#{bin}/{hookdeck-completion.bash,hookdeck-completion.zsh}"]
        system bin/"hookdeck", "completion", "--shell", "bash"
        system bin/"hookdeck", "completion", "--shell", "zsh"
        bash_completion.install "hookdeck-completion.bash"
        zsh_completion.install "hookdeck-completion.zsh"
        (zsh_completion/"_hookdeck").write <<~EOS
          #compdef hookdeck
          _hookdeck () {
            local e
            e=$(dirname ${funcsourcetrace[1]%:*})/hookdeck-completion.zsh
            if [[ -f $e ]]; then source $e; fi
          }
        EOS
      end
    end
  end

  def caveats; <<~EOS
    ❤ Thanks for installing the Hookdeck CLI! If this is your first time using the CLI, be sure to run `hookdeck login` first.
  EOS
  end
end
