# This file was generated by GoReleaser. DO NOT EDIT.
cask "hookdeck" do
  desc "Hookdeck CLI utility"
  homepage "https://hookdeck.com"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hookdeck"

  on_macos do
    on_intel do
      url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.0.4/hookdeck_1.0.4_darwin_amd64.tar.gz"
      sha256 "e19c0d84c4bbdd1b6435c5bfa80553d11dafb17253f0457196ec3e341c239800"
    end
    on_arm do
      url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.0.4/hookdeck_1.0.4_darwin_arm64.tar.gz"
      sha256 "a6f103f4d35995dcdb26d2893c8069c8dd8ec1c594ddfef5320552f9f276fb76"
    end
  end

  postflight do
    system "hookdeck", "completion", "--shell", "bash"
    system "hookdeck", "completion", "--shell", "zsh"
    bash_completion.install "hookdeck-completion.bash"
    zsh_completion.install "hookdeck-completion.zsh"
    (zsh_completion/"_hookdeck").write <<~EOS
      #compdef hookdeck
      _hookdeck () {
        local e
        e=$(dirname ${funcsourcetrace[1]%:*})/hookdeck-completion.zsh
        if [[ -f $e ]]; then source $e; fi
      }
    EOS
  end

  caveats do
    "❤ Thanks for installing the Hookdeck CLI! If this is your first time using the CLI, be sure to run `hookdeck login` first."
  end

  # No zap stanza required
end
