# This file was generated by GoReleaser. DO NOT EDIT.
cask "hookdeck" do
  desc "Hookdeck CLI utility"
  homepage "https://hookdeck.com"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hookdeck"

  on_macos do
    on_intel do
      url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.0.2/hookdeck_1.0.2_darwin_amd64.tar.gz"
      sha256 "5501649baecbd1ad84263ab8eb5117e5628af387bad1715c76e9344a7c095195"
    end
    on_arm do
      url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.0.2/hookdeck_1.0.2_darwin_arm64.tar.gz"
      sha256 "9db433f54935e93b858177b5ca049a4ba02b126e908a0746f675815684736473"
    end
  end

  postflight do
    system "hookdeck", "completion", "--shell", "bash"
    system "hookdeck", "completion", "--shell", "zsh"
    bash_completion.install "hookdeck-completion.bash"
    zsh_completion.install "hookdeck-completion.zsh"
    (zsh_completion/"_hookdeck").write <<~EOS
      #compdef hookdeck
      _hookdeck () {
        local e
        e=$(dirname ${funcsourcetrace[1]%:*})/hookdeck-completion.zsh
        if [[ -f $e ]]; then source $e; fi
      }
    EOS
  end

  caveats do
    "❤ Thanks for installing the Hookdeck CLI! If this is your first time using the CLI, be sure to run `hookdeck login` first."
  end

  # No zap stanza required
end
