# This file was generated by GoReleaser. DO NOT EDIT.
cask "hookdeck" do
  desc "Hookdeck CLI utility"
  homepage "https://hookdeck.com"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hookdeck"

  on_macos do
    on_intel do
      url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.0.1/hookdeck_1.0.1_darwin_amd64.tar.gz"
      sha256 "e43fd938e761f9761216ac5cc9c9a136d82b380d02db01d92124e56ede5dad33"
    end
    on_arm do
      url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.0.1/hookdeck_1.0.1_darwin_arm64.tar.gz"
      sha256 "bbb3250b3eab76c0246f9fc88e628557d07ed3515853e5d9ba29d0f24ebc2430"
    end
  end

  postflight do
    system "hookdeck", "completion", "--shell", "bash"
    system "hookdeck", "completion", "--shell", "zsh"
    bash_completion.install "hookdeck-completion.bash"
    zsh_completion.install "hookdeck-completion.zsh"
    (zsh_completion/"_hookdeck").write <<~EOS
      #compdef hookdeck
      _hookdeck () {
        local e
        e=$(dirname ${funcsourcetrace[1]%:*})/hookdeck-completion.zsh
        if [[ -f $e ]]; then source $e; fi
      }
    EOS
  end

  caveats do
    "❤ Thanks for installing the Hookdeck CLI! If this is your first time using the CLI, be sure to run `hookdeck login` first."
  end

  # No zap stanza required
end
