# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HookdeckBeta < Formula
  desc "Receive events (e.g. webhooks) on your localhost with event history, replay, and team collaboration"
  homepage "https://hookdeck.com"
  version "1.9.0-beta.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.9.0-beta.1/hookdeck_1.9.0-beta.1_darwin_amd64.tar.gz"
    sha256 "89fe0eff4e78940769d03f5c11d67b01594661b24dd93a3e4b30f11859045a00"

    def install
      bin.install "hookdeck"

      # Install completions from pre-generated files
      bash_completion.install "completions/hookdeck.bash" => "hookdeck"
      zsh_completion.install "completions/_hookdeck"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.9.0-beta.1/hookdeck_1.9.0-beta.1_darwin_arm64.tar.gz"
    sha256 "33d6059519cb7b1da682de8e490a2a67daafec7d638f8908b8d17f38ceb029f6"

    def install
      bin.install "hookdeck"

      # Install completions from pre-generated files
      bash_completion.install "completions/hookdeck.bash" => "hookdeck"
      zsh_completion.install "completions/_hookdeck"
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Hookdeck CLI!

      ⚠️  You are using a BETA version. Report issues at:
        https://github.com/hookdeck/hookdeck-cli/issues


      If this is your first time using the CLI, run:
        hookdeck login
    EOS
  end
end
