# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hookdeck < Formula
  desc "Receive events (e.g. webhooks) on your localhost with event history, replay, and team collaboration"
  homepage "https://hookdeck.com"
  version "1.9.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.9.0/hookdeck_1.9.0_darwin_amd64.tar.gz"
    sha256 "debff6025ecf5d616ea1bcd14f9590ee6f8191581c8120b68b9000d1ef8c9bdc"

    def install
      bin.install "hookdeck"

      # Install completions from pre-generated files
      bash_completion.install "completions/hookdeck.bash" => "hookdeck"
      zsh_completion.install "completions/_hookdeck"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.9.0/hookdeck_1.9.0_darwin_arm64.tar.gz"
    sha256 "ffb31c0adac70c5efedc3226798bae2b630e84f11c31f9571105b4b0143bf589"

    def install
      bin.install "hookdeck"

      # Install completions from pre-generated files
      bash_completion.install "completions/hookdeck.bash" => "hookdeck"
      zsh_completion.install "completions/_hookdeck"
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Hookdeck CLI!


      If this is your first time using the CLI, run:
        hookdeck login
    EOS
  end
end
