# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HookdeckBeta < Formula
  desc "Receive events (e.g. webhooks) on your localhost with event history, replay, and team collaboration"
  homepage "https://hookdeck.com"
  version "1.4.0-alpha.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.4.0-alpha.1/hookdeck_1.4.0-alpha.1_darwin_amd64.tar.gz"
    sha256 "36be6c4feb6816ef6564b50efe27b92b9631156c3dd931735fd3a304c7ca12e6"

    def install
      bin.install "hookdeck"

      # Install completions from pre-generated files
      bash_completion.install "completions/hookdeck.bash" => "hookdeck"
      zsh_completion.install "completions/_hookdeck"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.4.0-alpha.1/hookdeck_1.4.0-alpha.1_darwin_arm64.tar.gz"
    sha256 "30f6bfafe463dbcdb63341d46c2463e5795bdeb9414f43fbb133716ecaedb5f9"

    def install
      bin.install "hookdeck"

      # Install completions from pre-generated files
      bash_completion.install "completions/hookdeck.bash" => "hookdeck"
      zsh_completion.install "completions/_hookdeck"
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Hookdeck CLI!

      ⚠️  You are using a BETA version. Report issues at:
        https://github.com/hookdeck/hookdeck-cli/issues


      If this is your first time using the CLI, run:
        hookdeck login
    EOS
  end
end
