# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hookdeck < Formula
  desc "Receive events (e.g. webhooks) on your localhost with event history, replay, and team collaboration"
  homepage "https://hookdeck.com"
  version "1.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.1.0/hookdeck_1.1.0_darwin_amd64.tar.gz"
    sha256 "07cc837c437330eea9dcd5ee9151cfa6956096acfc1a973bb69590f3971f96cb"

    def install
      bin.install "hookdeck"

      # Install completions from pre-generated files
      bash_completion.install "completions/hookdeck.bash" => "hookdeck"
      zsh_completion.install "completions/_hookdeck"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.1.0/hookdeck_1.1.0_darwin_arm64.tar.gz"
    sha256 "25cd69e853e26892e6414e446b494864de855af5f923522ad4fd9fd1ccb2d358"

    def install
      bin.install "hookdeck"

      # Install completions from pre-generated files
      bash_completion.install "completions/hookdeck.bash" => "hookdeck"
      zsh_completion.install "completions/_hookdeck"
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Hookdeck CLI!

      If this is your first time using the CLI, run:
        hookdeck login
    EOS
  end
end
