# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HookdeckBeta < Formula
  desc "Receive events (e.g. webhooks) on your localhost with event history, replay, and team collaboration"
  homepage "https://hookdeck.com"
  version "1.8.0-beta.3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.8.0-beta.3/hookdeck_1.8.0-beta.3_darwin_amd64.tar.gz"
    sha256 "874d69fad2ce1cce29b729d7ad8c9a91a428a66c568147c7bd9ecd0ebeebdb0a"

    def install
      bin.install "hookdeck"

      # Install completions from pre-generated files
      bash_completion.install "completions/hookdeck.bash" => "hookdeck"
      zsh_completion.install "completions/_hookdeck"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.8.0-beta.3/hookdeck_1.8.0-beta.3_darwin_arm64.tar.gz"
    sha256 "7ab22f218e530976843e883f373d0efc4a6de6fcb97d5ef27724a550800f5e0c"

    def install
      bin.install "hookdeck"

      # Install completions from pre-generated files
      bash_completion.install "completions/hookdeck.bash" => "hookdeck"
      zsh_completion.install "completions/_hookdeck"
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Hookdeck CLI!

      ⚠️  You are using a BETA version. Report issues at:
        https://github.com/hookdeck/hookdeck-cli/issues


      If this is your first time using the CLI, run:
        hookdeck login
    EOS
  end
end
