# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hookdeck < Formula
  desc "Receive events (e.g. webhooks) on your localhost with event history, replay, and team collaboration"
  homepage "https://hookdeck.com"
  version "1.4.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.4.1/hookdeck_1.4.1_darwin_amd64.tar.gz"
    sha256 "ecd99a0c095fc536933d98a4e5eb91a892e45c911cb31249e17fe62c6106d3d7"

    def install
      bin.install "hookdeck"

      # Install completions from pre-generated files
      bash_completion.install "completions/hookdeck.bash" => "hookdeck"
      zsh_completion.install "completions/_hookdeck"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hookdeck/hookdeck-cli/releases/download/v1.4.1/hookdeck_1.4.1_darwin_arm64.tar.gz"
    sha256 "bfd6dab66a508d5e710af2a762789989031b96d6a726cb8a2c2d5cef1ba83b75"

    def install
      bin.install "hookdeck"

      # Install completions from pre-generated files
      bash_completion.install "completions/hookdeck.bash" => "hookdeck"
      zsh_completion.install "completions/_hookdeck"
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Hookdeck CLI!


      If this is your first time using the CLI, run:
        hookdeck login
    EOS
  end
end
